name: gamezoneR-data Scheduled Run
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
    reporter:
        runs-on: ubuntu-latest
        name: Updating GameZone data
        steps:
          - uses: actions/checkout@v2
          - name: Set up R ${{ matrix.r-version }}
            uses: r-lib/actions/setup-r@v2
            with:
              r-version: ${{ matrix.r-version }}
          - name: Install libcurl
            run: sudo apt-get install libcurl4-openssl-dev libssl-dev libicu-dev libxml2-dev
          - uses: r-lib/actions/setup-pandoc@v2
          - name: Install base dependencies
            run: |
              Rscript -e 'install.packages(c("remotes","glue","optparse","purrr","readr","rvest","usethis"))'
              Rscript -e 'remotes::install_github(repo = "JackLich10/gamezoneR")'
            env:
              GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          - name: Pull data and update files
            run: Rscript ./update.R --season 2022-23 --update_schedule TRUE --postseason FALSE --update_pbp TRUE
          - name: Commit files
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "Github Action"
              git pull
              git add ./data/.
              git commit -m "Updated master_schedules and play_by_play after latest bot run." || echo "No changes to commit"
          - name: Push updated files
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
